[project]
name = "xml-validator"
version = "1.0.0"
description = "Validate XML files using XSD or Schematron"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "lxml>=4.9.0",
    "tqdm>=4.65.0",
    "PyYAML>=6.0",
]

[project.scripts]
validate-xml = "xml_validator.cli:main"
